spring.application.name=userManagementSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/usermanagement
spring.datasource.username=postgres
**spring.datasource.password=superadmin123
spring.jpa.hibernate.ddl-auto=create

